PresentationLayer/Controllers/Extranet/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer;

namespace PresentationLayer.Controllers
{
    public class IndexController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListProducts()
        {
            try
            {
                return View(ProductsBL.Instance.ListProducts(0));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error");
            }
        }
    }
}

PresentationLayer/Controllers/Intranet/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EntitiesLayer;
using BusinessLayer;

namespace PresentationLayer.Controllers.Intranet
{
    public class CustomersController : Controller
    {
        /*PRINCIPAL LISTADO CLIENTES ACTIVOS*/
        [HttpGet]
        public ActionResult MaintaineCustomers()
        {
            try
            {
                List<CustomersEL> list = CustomersBL.Instance.ListClientes(0);
                return View(list);
            }
            catch (Exception e)
            {

                return RedirectToAction("Error", "Error", new { mensaje = e.Message });
            }
            
        }
        /*CLIENTES INACTIVOS*/
        [HttpGet]
        public ActionResult CustomersDown()
        {
            try
            {
                List<CustomersEL> list = CustomersBL.Instance.ListClientesDown(0);
                return View(list);
            }
            catch (Exception e)
            {

                return RedirectToAction("Error", "Error", new { mensaje = e.Message });
            }

        }
        [HttpGet]
        public ActionResult ActiveCustomersDown(Int16 idCustomer)
        {
            try
            {
                CustomersEL cliEnt = CustomersBL.Instance.SearchClientesDown(idCustomer);
                return View(cliEnt);
            }
            catch (Exception e)
            {
                return RedirectToAction("Error", "Error", new { mensaje = e.Message });
            }
        }
        [HttpPost]
        public ActionResult ActiveCustomersDown(FormCollection frm)
        {
            try
            {
                if (frm["btnActivar"] != null)
                {
                    int id = Convert.ToInt16(frm["lblId"]);
                    Boolean var = CustomersBL.Instance.ActiveCustomer(id);
                    if (var)
                    {
                        return RedirectToAction("CustomersDown");
                    }
                    else
                    {
                        return View();
                    }
                }
                else {
                    return RedirectToAction("CustomersDown");
                }

            }
            catch (Exception e)
            {
                return RedirectToAction("Error", "Error", new { mensaje = e.Message });
            }
        }
        /*NUEVO CLIENTE*/
        [HttpGet]
        public ActionResult CreateCustomers()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateCustomers(CustomersEL c)
        {
            try
            {
                Boolean var = CustomersBL.Instance.AddCustomer(c);
                if (var)
                {
                    return RedirectToAction("MaintaineCustomers");
                }
                else
                {
                    return View();
                }
            }
            catch (Exception e)
            {
                return RedirectToAction("Error", "Error", new { mensaje = e.Message });
            }
        }
        /*EDITAR CLIENTE*/
        [HttpGet]
        public ActionResult EditCustomers(Int16 idCustomer)
        {
            try
            {
                CustomersEL cliEnt = CustomersBL.Instance.SearchClientes(idCustomer);
                return View(cliEnt);
            }
            catch (Exception e)
            {

                return RedirectToAction("Error", "Error", new { mensaje = e.Message });
            }
            
        }
        [HttpPost]
        public ActionResult EditCustomers(CustomersEL c)
        {
            try
            {
                Boolean var = CustomersBL.Instance.EditCustomer(c);
                if (var)
                {
                    return RedirectToAction("MaintaineCustomers");
                }
                else {
                    return View();
                }
            }
            catch (Exception e)
            {
                return RedirectToAction("Error", "Error", new { mensaje = e.Message });
            }
        }
        /*ELIMINAR CLIENTE*/
        [HttpGet]
        public ActionResult DeleteCustomers(Int16 idCustomer)
        {
            try
            {
                CustomersEL cliEnt = CustomersBL.Instance.SearchClientes(idCustomer);
                return View(cliEnt);
            }
            catch (Exception e)
            {
                return RedirectToAction("Error", "Error", new { mensaje = e.Message });
            }
        }
        [HttpPost]
        public ActionResult DeleteCustomers(FormCollection frm)
        {
            try
            {
                if (frm["btnEliminar"] != null)
                {
                    int id = Convert.ToInt16(frm["lblId"]);
                    Boolean var = CustomersBL.Instance.DeleteCustomer(id);
                    if (var)
                    {
                        return RedirectToAction("MaintaineCustomers");
                    }
                    else
                    {
                        return View();
                    }
                }
                else {
                    return RedirectToAction("MaintaineCustomers");
                }

            }
            catch (Exception e)
            {
                return RedirectToAction("Error", "Error", new { mensaje = e.Message });
            }
        }
        /*DETALLES CLIENTE*/
        public ActionResult ViewCustomers(Int16 idCustomer)
        {
            CustomersEL cliEnt = CustomersBL.Instance.SearchClientes(idCustomer);
            return View(cliEnt);
        }

    }
}

PresentationLayer/Controllers/Intranet/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer;
using EntitiesLayer;

namespace PresentationLayer.Controllers.Intranet
{
    public class ProductsController : Controller
    {
        [HttpGet]
        public ActionResult MaintaineProducts()
        {
            List<ProductsEL> list = ProductsBL.Instance.ListProducts(0);
            
            return View(list);
        }
        [HttpGet]
        public ActionResult CreateProducts()
        {
            List<CategoriesEL> listCate = CategoriesBL.Instance.ListCategories();
            var listCategory = new SelectList(listCate, "idCategoria", "descripcionCat");
            ViewBag.ListCategory = listCategory;
            return View();
        }
        [HttpPost]
        public ActionResult CreateProducts(ProductsEL p)
        {
            try
            {
                Boolean var = ProductsBL.Instance.AddNewProducts(p);
                if (var)
                {
                    return RedirectToAction("MaintaineProducts");
                }
                else
                {
                    return View();
                }
            }
            catch (Exception e)
            {
                return RedirectToAction("Error", "Error", new { mensaje = e.Message });
            }
        }
        [HttpGet]
        public ActionResult EditProducts(Int16 idProducto)
        {
            try
            {
                List<CategoriesEL> listCate = CategoriesBL.Instance.ListCategories();
                var listCategory = new SelectList(listCate, "idCategoria", "descripcionCat");
                ViewBag.ListCategory = listCategory;
                ProductsEL prodEnt = ProductsBL.Instance.CallProductId(idProducto);
                return View(prodEnt);
            }
            catch (Exception e)
            {
                return RedirectToAction("Error", "Error", new { mensaje = e.Message });
            }
        }
        [HttpPost]
        public ActionResult EditProducts(ProductsEL p)
        {
            try
            {
                Boolean var = ProductsBL.Instance.EditProduct(p);
                if (var)
                {
                    return RedirectToAction("MaintaineProducts");
                }
                else {
                    return View();
                }
            }
            catch (Exception e)
            {
                return RedirectToAction("Error", "Error", new { mensaje = e.Message });
            }
        }
        public ActionResult ViewProducts(Int16 idProducto)
        {
            ProductsEL prodEnt = ProductsBL.Instance.CallProductId(idProducto);
            return View(prodEnt);
        }
    }
}

PresentationLayer/Views/MasterExtranet.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Store Flower</title>

    <!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
    <link href="~/Style/Extranet/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="~/Style/Extranet/css/freelancer.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/Style/Extranet/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
</head>
<body id="page-top" class="index">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#page-top">Store Flower</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="@Url.Action("ListProducts","Index")">Contenido</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about">Conocenos</a>
                    </li>
                    <li class="page-scroll">
                        
                        <a href="@Url.Action("Login","Intranet")">Intranet</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <!-- Header -->
    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <img style="width:256px;height:256px;" class="img-responsive" src="~/Style/Extranet/img/flower.png" alt="">
                    <div class="intro-text">
                        <span class="name">Store Flower</span>
                        <hr class="star-light">
                        <span class="skills">Arreglos Personalizados - Peluches - Delivery</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <section id="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Nuestros Productos</h2>
                    <hr class="star-primary">
                </div>
            </div>
            <div class="row">
                @RenderBody()
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal1" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="~/Style/Extranet/img/portfolio/cabin.png" class="img-responsive" alt="">
                    </a>
                </div>
            </div>
        </div>
    </section>
    <!-- About Section -->
    <section class="success" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>About</h2>
                    <hr class="star-light">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-lg-offset-2">
                    <p>Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional LESS stylesheets for easy customization.</p>
                </div>
                <div class="col-lg-4">
                    <p>Whether you're a student looking to showcase your work, a professional looking to attract clients, or a graphic artist looking to share your projects, this template is the perfect starting point!</p>
                </div>
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <a href="#" class="btn btn-lg btn-outline">
                        <i class="fa fa-download"></i> Download Theme
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h3>Location</h3>
                        <p>3481 Melrose Place<br>Beverly Hills, CA 90210</p>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>Around the Web</h3>
                        <ul class="list-inline">
                            <li>
                                <a href="https://www.facebook.com/manuel.guarniz.39" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="https://plus.google.com/u/0/+ManuelGuarnizCruz/posts" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                            </li>
                            <li>
                                <a href="https://twitter.com/cruzemg95" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>About Freelancer</h3>
                        <p>Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; Store Flower 2016
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-top page-scroll visible-xs visible-sm">
        <a class="btn btn-primary" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>

    <!-- Portfolio Modals -->
    <div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="modal-body">
                            <h2>Project Title</h2>
                            <hr class="star-primary">
                            <img src="~/Style/Extranet/img/portfolio/cabin.png" class="img-responsive img-centered" alt="">
                            <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
                            <ul class="list-inline item-details">
                                <li>
                                    Client:
                                    <strong>
                                        <a href="http://startbootstrap.com">Start Bootstrap</a>
                                    </strong>
                                </li>
                                <li>
                                    Date:
                                    <strong>
                                        <a href="http://startbootstrap.com">April 2014</a>
                                    </strong>
                                </li>
                                <li>
                                    Service:
                                    <strong>
                                        <a href="http://startbootstrap.com">Web Development</a>
                                    </strong>
                                </li>
                            </ul>
                            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery -->
    <script src="~/Style/Extranet/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="~/Style/Extranet/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="~/Style/Extranet/js/classie.js"></script>
    <script src="~/Style/Extranet/js/cbpAnimatedHeader.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="~/Style/Extranet/js/jqBootstrapValidation.js"></script>
    <script src="~/Style/Extranet/js/contact_me.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="~/Style/Extranet/js/freelancer.js"></script>

</body>
</html>

PresentationLayer/Views/MasterIntranet.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Menu Principal</title>
    <link href="~/Style/Intranet/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Style/Intranet/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">
    <link href="~/Style/Intranet/dist/css/sb-admin-2.css" rel="stylesheet">
    <link href="~/Style/Intranet/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Aministrador Store Flower</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#"><i class="fa fa-user fa-fw"></i> Perfil</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-gear fa-fw"></i> Configuracion</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Cerrar Sessión</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Principal</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-folder-open fa-fw"></i> Mantenedores<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("MaintaineProducts", "Products")"><i class="fa fa-tasks fa-fw"></i> Productos</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("MaintaineCustomers", "Customers")"><i class="fa fa-users fa-fw"></i> Clientes</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("CustomersDown", "Customers")"><i class="fa fa-trash fa-fw"></i> Clientes</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    @RenderBody()
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/Style/Intranet/bower_components/jquery/dist/jquery.min.js"></script>

    <script src="~/Style/Intranet/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <script src="~/Style/Intranet/bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <script src="~/Style/Intranet/dist/js/sb-admin-2.js"></script>
    
</body>
</html>